---
title: 'The Impact of Seasonal Malaria Chemoprevention in Benin Republic: A Retrospective Statistical Analysis'
author:
  - name: Sonounameto Roland Christel 
    orcid: 0009-0007-5841-4336
    corresponding: true
    email: roland.sonounameto@outlook.com
    roles:
      - Conception
      - Software
      - Writing the frit draft
    affiliations:
      - The African Institute for Mathematical Sciences-Research and Innovation Centre
  - name: to be added
    orcid: to be added
    corresponding: false
    roles: []
    affiliations:
      - to be added
license: CC BY-SA 4.0
keywords:
  - to be added
  - to be added
date: '2022-05-11'
abstract: |
  to be added
keypoints: to be added
citation:
  container-title: Notebooks Now!
draft: true
#bibliography: references.bib
echo: false
---

## Loading the necessary R packages

```{r filename = "Packages"}
#|message: false
#|warning: false
suppressMessages(suppressWarnings({
  if(!require("readxl")){install.packages("readxl", quiet = TRUE)}
  if(!require("stringr")){install.packages("stringr", quiet = TRUE)}
  if(!require("stringi")){install.packages("stringi", quiet = TRUE)}
  if(!require("chirps")){install.packages("chirps", quiet = TRUE)}
  if(!require("sf")){install.packages("sf", quiet = TRUE)}
  if(!require("rgeoboundaries")){install.packages("rgeoboundaries", quiet = TRUE)}
  if(!require("FNN")){install.packages("FNN", quiet = TRUE)}
  if(!require("tidyverse")){install.packages("tidyverse", quiet = TRUE)}
  if(!require("cobalt")){install.packages("cobalt", quiet = TRUE)}
  if(!require("MatchIt")){install.packages("MatchIt", quiet = TRUE)}
  if(!require("glmmTMB")){install.packages("glmmTMB", quiet = TRUE)}
  if(!require("splines")){install.packages("splines", quiet = TRUE)}
  if(!require("here")){install.packages("here", quiet = TRUE)}
}))

```


## The malaria cases and compleness data from 2017 to 2023 are imported.  
```{r}
source('code/month_fr_to_eng_function.R')
dataCases <- read_xlsx("processedData/casesMalariaBenin.xlsx", sheet = "casesData")
dataCompleteness <- read_xlsx("processedData/completudeData.xlsx", sheet = "completude")

dataCases$periodname_date <- lubridate::my(french_to_english(dataCases$periodname))
dataCases <- dataCases %>% 
          mutate(
            year = year(periodname_date),
            monthYear = format(periodname_date, "%B %Y")
          )
dataCases$periodname <-  str_replace_all(dataCases$periodname,
                                   c("Janvier" = "Jan", 
                                     "Février" = "Feb", 
                                     "Mars" = "Mar", 
                                     "Avril" = "Apr", 
                                     "Mai" = "May", 
                                     "Juin" = "Jun",
                                     "Juillet" = "Jul", 
                                     "Août" = "Aug", 
                                     "Septembre" = "Sep", 
                                     "Octobre" = "Oct", 
                                     "Novembre" = "Nov", 
                                     "Décembre" = "Dec"))


#==============================================================================
dataCases <-  dataCases %>% 
  filter(
    year != 2024
  ) %>% 
  mutate(
    HZs = case_when(
      HZs %in% c("Cotonou 1-Cotonou 4", "Cotonou 5", "Cotonou 2-Cotonou 3", "Cotonou 6") ~ "Cotonou",
      TRUE ~ HZs
    ), 
    HFs = ifelse(HFs == "CS Zounzonme" & HZs == "Bohicon-Za-kpota-Zogbodomey", 
                      "CS Zounzonme_BZZ", 
                      HFs),
         HFs = ifelse(HFs == "CS Partago" & HZs == "Bassila (ZS)", 
                      "CS Partago_Bassila", 
                      HFs),
         HFs = ifelse(HFs == "CS Deme" & HZs == "Bohicon-Za-kpota-Zogbodomey", 
                      "CS Deme_BZZ", 
                      HFs)
  ) 

#===============================================================================
dataCompleteness$periodname_date <- lubridate::my(french_to_english(dataCompleteness$periodname))
dataCompleteness <- dataCompleteness %>% 
          mutate(
            year = year(periodname_date),
            monthYear = format(periodname_date, "%B %Y")
          )
dataCompleteness$periodname <-  str_replace_all(dataCompleteness$periodname,
                                   c("Janvier" = "Jan", 
                                     "Février" = "Feb", 
                                     "Mars" = "Mar", 
                                     "Avril" = "Apr", 
                                     "Mai" = "May", 
                                     "Juin" = "Jun",
                                     "Juillet" = "Jul", 
                                     "Août" = "Aug", 
                                     "Septembre" = "Sep", 
                                     "Octobre" = "Oct", 
                                     "Novembre" = "Nov", 
                                     "Décembre" = "Dec"))



dataCompleteness <-  dataCompleteness %>% 
  filter(
    year != 2024
  ) %>% 
  mutate(
    HZs = case_when(
      HZs %in% c("Cotonou 1-Cotonou 4", "Cotonou 5", "Cotonou 2-Cotonou 3", "Cotonou 6") ~ "Cotonou",
      TRUE ~ HZs
    ), 
    HFs = ifelse(HFs == "CS Zounzonme" & HZs == "Bohicon-Za-kpota-Zogbodomey", 
                      "CS Zounzonme_BZZ", 
                      HFs),
         HFs = ifelse(HFs == "CS Partago" & HZs == "Bassila (ZS)", 
                      "CS Partago_Bassila", 
                      HFs),
         HFs = ifelse(HFs == "CS Deme" & HZs == "Bohicon-Za-kpota-Zogbodomey", 
                      "CS Deme_BZZ", 
                      HFs)
  )
```




```{r}

dataCasesCompletness <- dataCases %>%
                                  left_join(
                                    dataCompleteness %>% 
                                      select(periodname, HZs, HFs, expectedReports, actualReports), 
                                    by = c('periodname', 'HZs', 'HFs')
                                  )


dataCasesCompletness <- dataCasesCompletness %>% 
                                  group_by(periodname,HZs, HFs) %>% 
                                  mutate(
                                    
                                    totCases = sum(presumptiveUncompCases_U5,        
                                                     uncompCases_microscopyPositive_U5, 
                                                     uncompCases_RDTPositive_U5,
                                                     compCases_microscopyPositive_U5,
                                                     compCases_RDTPositive_U5,
                                                   presumptiveUncompCases_O5,        
                                                     uncompCases_microscopyPositive_O5, 
                                                     uncompCases_RDTPositive_O5,
                                                     compCases_microscopyPositive_O5,
                                                     compCases_RDTPositive_O5, na.rm = T
                                                   ),
                                    
                                    totCases_U5 = sum(presumptiveUncompCases_U5,        
                                                     uncompCases_microscopyPositive_U5, 
                                                     uncompCases_RDTPositive_U5,
                                                     compCases_microscopyPositive_U5,
                                                     compCases_RDTPositive_U5, na.rm = T
                                                    ),
                                    
                                    totCases_O5 = sum(presumptiveUncompCases_O5,        
                                                     uncompCases_microscopyPositive_O5, 
                                                     uncompCases_RDTPositive_O5,
                                                     compCases_microscopyPositive_O5,
                                                     compCases_RDTPositive_O5, na.rm = T
                                                    ),
                                    
                                    totTestedCases = sum(uncompCases_microscopyPositive_U5, 
                                                         uncompCases_RDTPositive_U5,
                                                         compCases_microscopyPositive_U5,
                                                         compCases_RDTPositive_U5,
                                                         uncompCases_microscopyPositive_O5, 
                                                         uncompCases_RDTPositive_O5,
                                                         compCases_microscopyPositive_O5,
                                                         compCases_RDTPositive_O5, na.rm = T
                                                      ),
                                    
                                    totTestedCases_U5 = sum(uncompCases_microscopyPositive_U5, 
                                                         uncompCases_RDTPositive_U5,
                                                         compCases_microscopyPositive_U5,
                                                         compCases_RDTPositive_U5, na.rm = T
                                                        ),
                                
                                    totTestedCases_O5 = sum(uncompCases_microscopyPositive_O5, 
                                                        uncompCases_RDTPositive_O5,
                                                        compCases_microscopyPositive_O5,
                                                        compCases_RDTPositive_O5, na.rm = T
                                                        ),
                                
                                    totUncompCases = sum(presumptiveUncompCases_O5,
                                                         presumptiveUncompCases_U5,
                                                         uncompCases_microscopyPositive_O5,
                                                         uncompCases_microscopyPositive_U5,
                                                         uncompCases_RDTPositive_O5,
                                                         uncompCases_RDTPositive_U5, na.rm = T
                                                        ),
                                    
                                    totUncompCases_U5 = sum(presumptiveUncompCases_U5,
                                                         uncompCases_microscopyPositive_U5,
                                                         uncompCases_RDTPositive_U5, na.rm = T
                                                        ),
                                    
                                    totUncompCases_O5 = sum(presumptiveUncompCases_O5,
                                                         uncompCases_microscopyPositive_O5,
                                                         uncompCases_RDTPositive_O5, na.rm = T
                                                        ),
                                    
                                    totTestedUncompCases_U5 = sum(
                                                         uncompCases_microscopyPositive_U5,
                                                         uncompCases_RDTPositive_U5, na.rm = T
                                                        ),
                                    
                                    totTestedUncompCases_O5 = sum(
                                                         uncompCases_microscopyPositive_O5,
                                                         uncompCases_RDTPositive_O5, na.rm = T
                                                        ),
                                    
                                    totCompCases = sum(presumptiveCompCases_O5,
                                                         presumptiveCompCases_U5,
                                                         compCases_microscopyPositive_O5,
                                                         compCases_microscopyPositive_U5,
                                                         compCases_RDTPositive_O5,
                                                         compCases_RDTPositive_U5, na.rm = T
                                                        ),
                                    
                                    totCompCases_U5 = sum(presumptiveCompCases_U5,
                                                         compCases_microscopyPositive_U5,
                                                         compCases_RDTPositive_U5, na.rm = T
                                                        ),
                                    
                                    totCompCases_O5 = sum(presumptiveCompCases_O5,
                                                         compCases_microscopyPositive_O5,
                                                         compCases_RDTPositive_O5, na.rm = T
                                                        ),
                                    
                                    totTestedCompCases_U5 = sum(
                                                         compCases_microscopyPositive_U5,
                                                         compCases_RDTPositive_U5, na.rm = T
                                                        ),
                                    
                                    totTestedCompCases_O5 = sum(
                                                         compCases_microscopyPositive_O5,
                                                         compCases_RDTPositive_O5, na.rm = T
                                                        ),
                                    
                                    totDeaths             = sum(
                                                                deathsCompCases_testPositive_O5,
                                                                deathsCompCases_testPositive_U5,
                                                                presumptiveDeathsComp_O5,
                                                                presumptiveDeathsComp_U5,na.rm = T
                                                               ),
                                    totTestedDeaths       = sum(
                                                                deathsCompCases_testPositive_O5,
                                                                deathsCompCases_testPositive_U5,
                                                                na.rm = T
                                                               ),
                                    
                                    totTestedDeaths_U5    = sum(
                                                                deathsCompCases_testPositive_U5,
                                                                na.rm = T
                                                               ),
                                    
                                    totTestedDeaths_O5    = sum(
                                                                deathsCompCases_testPositive_O5,
                                                                na.rm = T
                                                               )
                                  )






```




